version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=hieubeo
      - POSTGRES_PASSWORD=0612
      - POSTGRES_DB=nest
    networks:
      - bookingapp
networks:
  bookingapp:
